server:
  port: 1001
  servlet.context-path: /customer-register # It is the root Uri eg: http://localhost:1001/customer-register/customer/addCustomer

spring:
  application:
    name: customer-application
  data:
    mongodb:
      database: Customers
      host: localhost
      port: 27017

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.format_sql: true